config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #create
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create", as: :task_create
  #read
  get "tasks", to: "tasks#index", as: :tasks
  get "tasks/:id", to: "tasks#show", as: :task
  #edit
  get "/tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "/tasks/:id", to: "tasks#update"
  #delete
  delete "/tasks/:id", to: "tasks#destroy", as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end


  def show
    @task = Task.find(params[:id])
  end


  def new
    @task = Task.new
  end

  def create
  Task.create!(params.require(:task).permit(:title,:details))
  redirect_to tasks_path
  end

  def edit
  @task = Task.find(params[:id])

  end

  def update
    @task = Task.find(params[:id])
    @task.update(params.require(:task).permit(:title,:details))
    redirect_to tasks_path(@task.id)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <div >
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div >
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1> My tasks :  </h1>
<% @tasks.each do |task|  %>
    <input type="checkbox"> <%= link_to task.title, task_path(task.id) %>
    <%= link_to "delete", delete_task_path(task.id), method: :delete %>

<% end  %>

<br>
<btn> <%= link_to "add a new task", tasks_new_path %> </btn>

app/views/tasks/new.html.erb
<!-- <form action="/tasks" method="post">
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>

  <label for="title">title: </label>
  <input type="string" name="task[title]" id="title">

  <label for="details">details: </label>
  <input type="text" name="task[details]" id="details">

  <input type="submit">
</form> -->

<%= form_for(@task) do |f| %>
  <div >
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div >
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1> <%= @task.title %> </h1>

<ul>
 <li> <%= @task.id %></li>
 <li> <%= @task.details %></li>
 <li> <%= @task.completed %></li>
</ul>

<p> <%= link_to "go back", tasks_path  %></p>

<br>

<%= link_to "edit", edit_task_path(@task.id)  %>